### ISSUE TITLE
Official raycast store submission

### ISSUE THREAD

**Issue by Paikan** [aurelticot/raycast-omnivore#4]
Hello,

Thanks for this nice work.

Have you submitted it to be part of the raycast store?

Best.

**Comment by aurelticot** [comment]
Hey,

There were some discussions in the Omnivore repo (https://github.com/omnivore-app/omnivore/issues/1578) to be maintained there and submitted as an official Omnivore extension but it didn't catch the attention of the main maintainer (not blaming, probably busy on the core of the app). There was also another initiative in parallel with interesting features.

That's why I haven't published to the Raycast store.

I'll try to follow-up but if there's not much traction, I'll eventually publish.

Thanks

**Comment by Paikan** [comment]
Makes sense.

Thanks for your quick reply.
